spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 993199802086-0p22pu2ffpkdu7gig8sru04r8luhkses.apps.googleusercontent.com
            client-secret: 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
            scope:
              - name
              - email