spring :
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test

  sql:
    init:
      data-location: classpath*:db/h2/data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

